[package]
name = "sfuzz"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
byteorder = "1.4"
elfparser = { git = "https://github.com/seal9055/local_crates/", branch = "main" }
