#!/bin/sh
#
# Copyright 2013 Canonical Ltd.
#
# Author: Alberto Milone <alberto.milone@canonical.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
LOG=/var/log/prime-supported.log

if [ -n "$1" ]; then
    LOG="$1"
fi

# Remove any previous logs
# as long as the log is an actual
# file. In some cases we may pass
# it /dev/stdout which is a link
if [ -f $LOG ]; then
    rm -f $LOG
fi

if [ -e "/var/lib/ubuntu-drivers-common/requires_offloading" ]; then
    echo "Requires offloading" >> $LOG 2>&1
    echo "yes"
else
    echo "No offloading required. Abort" >> $LOG 2>&1
    exit 0
fi

